# YOUR NAME OR TITLE OF YOUR SITE
name: "Chad Theory"

# YOUR BRAND/PERSONAL TAGLINE
tagline: "Independent Australian Conservative Podcast"
# YOUR/BRAND IMAGE URL
Image_URL:  https://chadtheory.github.io/assets/images/brand_image.jpg

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image:  /assets/images/channels4_banner.jpg

# SOCIAL MEDIA 
links:
  # YOUTUBE
  - 
    Name: YouTube
    URL: https://www.youtube.com/channel
    Username: UC4Qds0oLcK7StlakgvGVJug
    Color: '#ff0000'
    Icon-Class: fab fa-youtube
  # Anchor
  -
    Name: Podcast
    URL: https://anchor.fm/chad-theory
    Icon-Class: fa fa-podcast
    Color: '#1DB954'
    Text_Color: '#ffffff'
  # PAYPAL 
  - 
    Name: Paypal Donation
    URL: https://www.paypal.com/donate/?hosted_button_id=VCXXRH8RWLRNQ
    Icon-Class: fab fa-paypal
    Color: '#003087'
    Text_Color: '#ffffff'
  # FACEBOOK 
  - 
    Name: Facebook
    URL: https://www.facebook.com
    Username: chadtheoryshow
    Color: '#3b5998'
    Icon-Class: fab fa-facebook
  # INSTAGRAM
  - 
    Name: Instagram
    URL: https://www.instagram.com
    Username: chadtheoryshow
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram    
    Text_Color: '#ffffff'

  # TWITTER
  - 
    Name: Twitter
    URL: https://twitter.com
    Username: chadtheoryshow
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter
  
  # DISCORD
# - 
#   Name: Discord
#   URL: 'https://discord.gg'
#   Username: aF55TQNcSC
#   Icon-Class: fab fa-discord
#   Color: '#5865F2'
#   Text_Color: '#ffffff'
     

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: #'Yes'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
